[package]
name = "indexer_base"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2024"

[dependencies]
log.workspace = true
serde = { workspace = true , features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
