[package]
name = "merging"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2024"

[lints]
workspace = true 

[dependencies]
log.workspace = true
serde = { workspace = true , features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
