[package]
name = "merging"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
indexer_base = { path = "../indexer_base" }
processor = { path = "../processor" }
dlt = { path = "../dlt" }
crossbeam-channel = "0.4"

[dev-dependencies]
tempdir = "0.3"
test-generator = "0.2.2"
pretty_assertions = "0.6"
log4rs = "0.8"