[package]
name = "merging"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
# dlt = { path = "../dlt" }
indexer_base = { path = "../indexer_base" }
log = "0.4"
processor = { path = "../processor" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio-stream = "0.1.8"
tokio-util = "0.7"

[dev-dependencies]
tempdir = "0.3"
test-generator = "0.3.0"
pretty_assertions = "1.0"
log4rs = "1.0"