[package]
name = "merging"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
indexer_base = { path = "../indexer_base" }
processor = { path = "../processor" }
dlt = { path = "../dlt" }

[dev-dependencies]
tempdir = "0.3"
test-generator = "0.2.2"
pretty_assertions = "0.6"