[package]
name = "merging"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6.3", features = ["attributes", "unstable"] }
crossbeam-channel = "0.5.0"
dlt = { path = "../dlt" }
futures = { version = "0.3.4", features = ["std", "async-await"], default-features = false }
indexer_base = { path = "../indexer_base" }
log = "0.4"
processor = { path = "../processor" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempdir = "0.3"
test-generator = "0.3.0"
pretty_assertions = "0.6"
log4rs = "0.13.0"