[package]
name = "logviewer_parser"
version = "0.4.6"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
regex = "1.0.5"
quicli = "0.4"
structopt = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1.5"

[dev-dependencies]
rand = "0.6.5"
pretty_assertions = "0.6.1"
tempdir = "0.3"
