[package]
name = "dlt"
version = "0.2.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2021"

[dependencies]
buf_redux = "0.8"
bytes = "1.0"
chrono = "0.4"
crossbeam-channel = "0.5"
dirs = "4.0"
dlt-core = "0.13"
# dlt-core = { path = "../../../../../dlt-core.git" }
etherparse = "0.10"
humantime = "2.1"
indexer_base = { path = "../indexer_base" }
lazy_static = "1.4"
log = "0.4"
parsers = { path = "../parsers" }
pcap-parser = "0.13"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.5", features = ["full"] }
tokio-stream = "0.1.5"
tokio-util = {version = "0.6", features = ["codec", "net"] }

[dev-dependencies]
rand = "0.8"
pretty_assertions = "1.0"
env_logger = "0.9"


