[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
serde.workspace = true
anyhow.workspace = true
axum = { version = "0.7", features = ["macros"] }
rmcp = { version = "0.11", features = [
  "client",
  "macros",
  "reqwest",
  "schemars",
  "server",
  "transport-io",
  "transport-streamable-http-client-reqwest",
  "transport-streamable-http-server",
  "transport-streamable-http-server-session",
] }
schemars = "1.1"
tokio.workspace = true
tokio-util.workspace = true
log.workspace = true
reqwest = "0.12.25"
thiserror.workspace = true
