[package]
name = "plugins_host"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
log.workspace = true
dirs.workspace = true
toml.workspace = true
blake3.workspace = true
rand.workspace = true
wasmtime = "32.0"
wasmtime-wasi = "32.0"
uuid = { workspace = true , features = ["serde", "v4"] }
components = { path = "../components" }
parsers = { path = "../parsers" }
sources = { path = "../sources" }
stypes = { path = "../stypes" }
definitions = { path = "../definitions" }
# TODO : Introduce shared crates and move dir_checksum to it.
dir_checksum = { path = "../../../../cli/development-cli/dir_checksum" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }

[[bench]]
name = "plugin_parser_init"
harness = false

