[package]
name = "plugins_host"
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
tokio.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
dirs.workspace = true
toml.workspace = true
blake3.workspace = true
rand.workspace = true

wasmtime = "33.0"
wasmtime-wasi = "33.0"

parsers = { path = "../parsers" }
stypes = { path = "../stypes" }
# TODO : Introduce shared crates and move dir_checksum to it.
dir_checksum = { path = "../../../../cli/development-cli/dir_checksum" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
processor = { path = "../processor"}

[[bench]]
name = "plugin_parser_init"
harness = false

