[package]
name = "text_grep"
version = "0.1.0"
edition = "2024"

[lib]
name = "text_grep"
crate-type = ["lib"]
path = "src/lib.rs"

[lints]
workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { workspace = true, features = ["full"] }
bufread = { path = "../bufread" }
tokio-util.workspace = true
grep-searcher.workspace = true
grep-regex.workspace = true
thiserror.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
