[package]
name = "indexer_cli"
version = "0.35.2"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33.3"
crossbeam-channel = "0.5.1"
dirs = "3.0.1"
dlt = { path = "../dlt" }
dlt-core = "0.11.0"
# dlt-core = { git = "https://github.com/DmitryAstafyev/dlt-core.git" }
# dlt-core = { path = "../../../../../dlt-core.git" }
env_logger = "0.8.3"
indexer_base = { path = "../indexer_base" }
indicatif = "0.15.0"
lazy_static = "1.4.0"
log = "0.4"
merging = { path = "../merging" }
processor = { path = "../processor" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.5", features = ["full"] }
