[package]
name = "indexer_cli"
version = "0.35.1"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
clap = "2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
log = "0.4"
log4rs = "0.8"
dirs = "2.0"
dlt = { path = "../dlt" }
processor = { path = "../processor" }
indexer_base = { path = "../indexer_base" }
merging = { path = "../merging" }
crossbeam-channel = "0.4"
async-std = "1.4"
