[package]
name = "indexer_cli"
version = "0.35.2"
authors = ["esrlabs.com"]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.2"
bytes = "1.0"
chrono = "0.4"
clap = { version = "3.0", features = ["cargo"] }
# clap = "2.33.3"
crossbeam-channel = "0.5.1"
dirs = "4.0"
dlt-core = "0.14"
# dlt-core = { path = "../../../../../dlt-core.git" }
env_logger = "0.9"
futures = "0.3"
indexer_base = { path = "../indexer_base" }
indicatif = "0.16"
lazy_static = "1.4"
log = "0.4"
merging = { path = "../merging" }
parsers = { path = "../parsers" }
processor = { path = "../processor" }
sources = { path = "../sources" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.5", features = ["full"] }
tokio-util = {version = "0.7", features = ["codec", "net"] }
tokio-stream = "0.1.5"
