[package]
name = "dlt-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
dlt-core.workspace = true
indexer_base = { path = "../../indexer_base" }
log.workspace = true
parsers = { path = "../../parsers" }
sources = { path = "../../sources" }
processor = { path = "../../processor"}
tokio = { workspace = true , features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "net"] }

[dev-dependencies]
