[package]
name = "chipmunk_integration"
version = "0.2.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "chipmunk_integration"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.5.3"

[target.'cfg(windows)'.build-dependencies]
cc = "1.0"

[dependencies]
anyhow = "1.0.34"
crossbeam-channel = "0.5.0"
dirs = "3.0.1"
dlt = { path = "../../indexer/dlt" }
indexer_base = { path = "../../indexer/indexer_base" }
log = "0.4"
log4rs = "0.13.0"
merging = { path = "../../indexer/merging" }
neon = { version = "0.5.3", features = ["event-handler-api"] }
processor = { path = "../../indexer/processor" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum_macros = "0.20.1"
tempfile = "3.1.0"
thiserror = "1.0.22"
tokio = { version = "0.3.5", features = ["full"] }