[package]
name = "parsers"
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
byteorder = "1.5"
chrono = "0.4"
chrono-tz = "0.10"
dlt-core = { workspace = true, features = ["serialization", "fibex"] }
lazy_static.workspace = true
log.workspace = true
regex.workspace = true
memchr = "2.7"
serde = { workspace = true , features = ["derive"] }
thiserror.workspace = true
rand.workspace = true
someip-messages = { git = "https://github.com/esrlabs/someip" }

# NOTE: Pinned to a specific commit because our unsafe code in `someip.rs`
# depends on the internal implementation of this library.
# Verify safety contract on update.
someip-payload = { git = "https://github.com/esrlabs/someip-payload", rev= "b9aa52c96fcbdb0e5aa1ee5258299f0ff7e3a094" }
someip-tools = { path = "../addons/someip-tools" }

[dev-dependencies]
stringreader = "0.1"
