[package]
name = "parsers"
version = "0.1.0"
edition = "2021"

[dependencies]
buf_redux = "0.8"
byteorder = "1.4"
crossbeam-channel = "0.5"
chrono = "0.4"
chrono-tz = "0.8"
dlt-core = "0.14"
humantime = "2.1"
lazy_static = "1.4"
log = "0.4.17"
memchr = "2.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio-util = "0.7"
rand = "0.8.5"
# someip-messages = { path = "../../../../../someip"}
someip-messages = { git = "https://github.com/esrlabs/someip" }
# someip-payload = { path = "../../../../../someip-payload" }
someip-payload = { git = "https://github.com/esrlabs/someip-payload" }

[dev-dependencies]
stringreader = "0.1.1"
env_logger = "0.10"