[package]
name = "parsers"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5"
chrono = "0.4"
chrono-tz = "0.10"
dlt-core.workspace = true
lazy_static.workspace = true
log.workspace = true
regex.workspace = true
memchr = "2.7"
serde = { workspace = true , features = ["derive"] }
thiserror.workspace = true
rand.workspace = true
someip-messages = { git = "https://github.com/esrlabs/someip" }
someip-payload = { git = "https://github.com/esrlabs/someip-payload" }
someip-tools = { path = "../addons/someip-tools" }
stypes = { path = "../stypes", features=["rustcore"] }
uuid = { workspace = true , features = ["serde", "v4"] }
components = { path = "../components" }

[dev-dependencies]
stringreader = "0.1"
