[workspace]

members = [
    "dlt",
    "indexer_base",
    "indexer_cli",
    "merging",
    "parsers",
    "processor",
    "session",
    "sources",
]

# only uncomment when profiling
[profile.release]
debug = true
