[package]
name = "shell-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
which.workspace = true
log.workspace = true
stypes = { path = "../../stypes", features=["rustcore"]  }

[lints]
workspace = true
