[package]
name = "processor"
authors = ["esrlabs.com"]
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
bincode = "1.3"
bufread.workspace = true
bytecount = "0.6"
futures.workspace = true
grep-regex.workspace = true
grep-searcher.workspace = true
indexer_base.workspace = true
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
parsers.workspace = true
sources.workspace = true
regex.workspace = true
serde = { workspace = true , features = ["derive"] }
serde_json.workspace = true
text_grep.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
stypes = { workspace = true, features=["rustcore"] }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
pretty_assertions = "1.4"
rand.workspace = true
tempfile.workspace = true
tokio.workspace = true
plugins_host.workspace = true
toml.workspace = true

[[bench]]
name = "map_benchmarks"
harness = false

[[bench]]
name = "dlt_producer"
harness = false

[[bench]]
name = "someip_producer"
harness = false

[[bench]]
name = "someip_legacy_producer"
harness = false

[[bench]]
name = "text_producer"
harness = false

[[bench]]
name = "plugin_praser_producer"
harness = false

[[bench]]
name = "mocks_once_producer"
harness = false

[[bench]]
name = "mocks_once_parallel"
harness = false

[[bench]]
name = "mocks_multi_producer"
harness = false

[[bench]]
name = "mocks_multi_parallel"
harness = false
