[package]
name = "processor"
version = "0.2.0"
authors = ["esrlabs.com"]
edition = "2021"

[dependencies]
thiserror = "1.0"
bincode = "1.3"
buf_redux = "0.8"
bytecount = "0.6"
chrono = "0.4"
crossbeam-channel = "0.5"
encoding_rs_io = "0.1.7"
futures = "0.3"
grep-matcher = "0.1.4"
grep-regex = "0.1.8"
grep-searcher = "0.1.7"
grep-printer = "0.1.5"
indexer_base = { path = "../indexer_base" }
itertools = "0.10.0"
lazy_static = "1.4"
log = "0.4"
nom = "7.1"
parsers = { path = "../parsers" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sources = { path = "../sources" }
tokio = { version = "1.5", features = ["full"] }
termcolor = "1.1"
tokio-util = "0.7"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}
dirs = "4.0"
env_logger = "0.9"
pretty_assertions = "1.0"
proptest = "1.0"
proptest-derive = "0.3"
rand = "0.8"
tempfile = "3.2"
test-generator = "0.3"

[[bench]]
name = "map_benchmarks"
harness = false

[[bench]]
name = "parse_benchmarks"
harness = false
