[package]
name = "processor"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
bincode = "1.3.1"
buf_redux = "0.8.1"
bytecount = "0.6.0"
chrono = "0.4"
crossbeam-channel = "0.5.0"
encoding_rs_io = "0.1.7"
futures = { version = "0.3.4", features = ["std", "async-await"], default-features = false }
indexer_base = { path = "../indexer_base" }
lazy_static = "1.4.0"
log = "0.4"
nom = "5.1.2"
regex = "1"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3.3"
dirs = "3.0.1"
env_logger = "0.8.1"
pretty_assertions = "0.6"
proptest = "0.10.1"
proptest-derive = "0.2.0"
rand = "0.7"
tempfile = "3.1"
test-generator = "0.3.0"
tokio = { version = "0.3.3", features = ["full"] }

[[bench]]
name = "parse_benchmarks"
harness = false